### ISSUE TITLE
no kernel folder generated

### ISSUE THREAD

**Issue by CcCc1101** [nqdu/JDSurfG#1]
I have successfully compiled and installed the software. When running example, there is no kernel folder generated.
There is no error when compiling and running the program.
Want to know why. Thank you very much

**Comment by nqdu** [comment]
I think I forgot to mention that in the DOC. Actually, the kernel folder is only a temporary folder when running this program, and it is removed after iterations. If you want to keep it, please comment out the line:
```
int ierr = system("rm -r kernel");
```
in `src/Surftomo/main.cpp` and `src/JointTomo/main.cpp`

**Comment by CcCc1101** [comment]
I have followed your suggest and  commented the line:
`int ierr = system("rm -r kernel");`
in `src/Surftomo/main.cpp` and `src/JointTomo/main.cpp`. The kernel can be generated but it's empty.
May be, you removed the kernel output using `int ierr = system(("rm -r "+ filename).c_str() );`
 in `src/SurfaceWave/SurfaceWave.cpp`. 
I will try it, thank you very much
