### ISSUE TITLE
About using the script 01_get_grd.sh with the prompt

### ISSUE THREAD

**Issue by liuyzxinxiuer** [nqdu/JDSurfG#10]
Hello, About using the script 01_get_grd.sh with the prompt . /01_get_grd.sh: 15: . /01_get_grd.sh: Syntax error: Bad for loop variable, don't know how to solve it and would like to consult you. I would like to ask you which programs should be used to draw the results of the example using JDsurfg, and which files should be modified to apply JDsurfg to other areas. I'm studying this for the first time independently, and I feel like I can't get my head around a lot of things. I appreciate it and look forward to your reply, thank you!

**Comment by nqdu** [comment]
Hi,

You may copy the whole `plot` directory to your working directory, and try to create figures here. Then you can check parameters in `plots/parameters.sh`, make sure the `RESULT_DIR`(`result` or `resultJ`) and `MODEL` (final model index) match exactly with what you want.

**Comment by liuyzxinxiuer** [comment]
Thank you very much! After running 01_get_grd.sh, which reported an error, I found that there was no data within some of the generated ture.dat files. So, I found the script generate_ckbd_model.bak.py and found zstr = “ 0.0000 2.0000 4.0000 6.0000 8.0000 10.0000 12.0000 14.0000 16.0000 18.0000 20.0000 24.0000 28.0000 32.0000 36.0000 40.0000 45.0000 50.0000 55.0000 60.0000 70.0000 80.0000 90.0000 100.0000 110.0000” line of code, the resulting ture.dat file number is different. Not sure why this is. Thank you very much for your help!

**Comment by nqdu** [comment]
Hi,
The example in the `example` directory is not a checkerboard model. It only contains 3 anomaly blocks. 

If you want to do a real checkerboard test, you can try to use `generate_ckbd_model.py`.

**Comment by liuyzxinxiuer** [comment]
Thank you very much, I would like to ask how to fully utilize this generate_ckbd_model.py script, I know about modifying “x0,y0 nlon,nlat dx,dy zstr” in the script and about the dx,dy information in the script about mod.true. It's not clear what other parts need to be changed and what to look for. I apologize for asking you such basic knowledge, I'm a bit lost. Thank you very much for your help.

**Comment by nqdu** [comment]
hi, the checkerboard model is given by adding perturbation to a 1-D model. The 1-D model is (you could find the lines in the script and create your own modification):
```python
for i in range(nz):
    v[i,:,:] = 2.5 + 0.02 * z[i]
```
and perturbation is
```python
v0 = 0.1 * np.sin(xx[k] * nlevelx) * np.sin(yy[j] * nlevely) * np.sin(zz[i] * nlevelz)
```
So the output checkerboard model is `v = v * ( 1 + v0)`. The checkerboard size is given in index level (not in the real units), you can choose different `levelx/y/z` and have a look at the output figures to decide if that's your want.

**Comment by liuyzxinxiuer** [comment]
Hi, I just searched your email for advice and found that it was frozen. I'm in my first year of study and I'm confused as I'm approaching this for the first time on my own. There are some misunderstandings in the literature and manuals. I have applied DSurfTomo to the East Tectonic Knot region, and I keep getting errors when I run the program. I would like to consult you on what the problem is.
    Below is a picture of my setup (and a picture of the run is attached):
    This CE.dat dispersion file has a period of 10-50 as described in the literature, and the depth of the velocity parameter model as described in the literature is 2.5 for the first 10km interval, and 5 for the last 10-60 intervals, so I set the period of the dispersion data to 5 as well.
    Using generate that script to generate the model, I selected the upper left corner as the northwest point (28.5, 97.5) based on the literature illustration. The 0.5 x 0.5° was selected as well as the number of depth grids from the literature. Didn't change much of the rest.
    Your help is much appreciated!

<img width="652" alt="341e27e9cade3e4cf885931bce9e4f5" src="https://github.com/user-attachments/assets/9212d869-29d2-4561-9a73-d22b07366e89">
<img width="652" alt="341e27e9cade3e4cf885931bce9e4f5" src="https://github.com/user-attachments/assets/3ec2880f-9c1c-484e-9dd8-011b71e044b9">
<img width="431" alt="af927afc349275d211ea013689de448" src="https://github.com/user-attachments/assets/89bca97c-fd6d-49b1-8fa1-af21120ff913">
<img width="878" alt="b14e919bdeeb11835bd6c9eceb53da3" src="https://github.com/user-attachments/assets/8375d2de-d850-4007-be1c-def3d55a891a">
<img width="787" alt="e67a06260a13f7f554f68931eadd5d6" src="https://github.com/user-attachments/assets/cb0d519e-3985-4459-9ca3-6c0a159943be">

**Comment by nqdu** [comment]
Hi,several suggestions you may want to try:

1.  What do you want to do? checkerboard test or real data? Could you also provide the command (how do you launch `DSurfTomo`) for running this program?
2.  If everything is correct, I strongly suggest you to have a look on your dispersion data file. One  debugging tips: remove `-DEIGEN_NO_DEBUG` option in CMakeLists.txt, delete your `build` directory, and try to reinstall. Then you can run it again and see which part is problematic.

**Comment by liuyzxinxiuer** [comment]
I am re-doing the data from the article on Southeast Tibet by you and Mr. Chen Haopeng. Sorry for the discovery, I neglected to choose real data or checkerboard modeling inside the reference file. I chose real data and followed the literature in choosing the inversion method of LSMR. But the error was reported like this
Iteration 1
computing Surface Wave 1-D Frechet Kernel ...
computing traveltimes and 2-D Frechet Kernel ...
Segmentation fault (core dumped)
I think Mr. Sensei you didn't adjust the parameters in the generation MOD you mentioned before. I checked your article and I think it's this part “ v[i,:,:] = 2.5 + 0.02 * z[i]” that I didn't modify properly. I realized that the velocity, 2.5, is the value of the velocity out at 0km, but I don't seem to find the corresponding velocity at 0km underneath the articles by Haopeng Chen and you. Sensei do you think my understanding is correct, is it the speed parameter inside the MOD that should be modified?
Thank you very much for your patience and help, Mr. Teacher, it's very touching, thank you.

**Comment by nqdu** [comment]
Hi,

1. Could you provide a screenshot of what's going on? (including command line, output/errors).
2. 0km-depth is not usually well constrained due to the smoothing/frequency used. so I usually discard it.
3. for the `segmentation fault` error, can you try the second option from my previous response？

Good luck

**Comment by liuyzxinxiuer** [comment]
I really appreciate your help, maybe I'm a bit stupid and really didn't realize what the problem is here.I'm sorry for the trouble.
I haven't tried the things you mentioned above, I will finish this as soon as I can.
I do this part with real data. I hope you can help me to see what the problem is. Here is how I ran it:
<img width="887" alt="e1a8eaf7ba9490a61b52576bc8dca20" src="https://github.com/user-attachments/assets/f05c49e4-c0ce-4036-8587-1cc202809ce0">
<img width="614" alt="a9fbda339aba325d72198da1eda7f02" src="https://github.com/user-attachments/assets/f8f5eb0f-b8b4-4bf3-a057-ba70edf7b697">
<img width="897" alt="fe86afd2ba04477f19cb34c96b65c56" src="https://github.com/user-attachments/assets/376f2a53-1695-4dfc-8035-9dc673b08268">
<img width="218" alt="ad7c48434b8b29a66124facc6e1e4eb" src="https://github.com/user-attachments/assets/72e6b174-a77c-41e4-b313-a67aaf826f69">

**Comment by liuyzxinxiuer** [comment]
I just checked the CE.dat file with gmtinfo and found that the data change range is <28.898/31.909> <91.759/98.427> <2.906/3.629>, but Mr. Chen Haopeng's literature paper says the region range is from 22 to 22 and from 98 to 105, so the data is not overlapping with the region. of the region, doesn't this data not overlap with the region?

**Comment by nqdu** [comment]
I just have a quick look on your model. The lat/lon in the MOD.in should be the northwest point of your model. However, in your model, it seems many stations are out of this region. Could you have a double check?

BTW, could you paste the command you execute to launch this program? (like ./DSurfTomo surfdata.txt MOD.in)
