### ISSUE TITLE
Can JDSurfG can do some 2D surface wave tomography inversion?

### ISSUE THREAD

**Issue by xichaoqiang** [nqdu/JDSurfG#2]
Can JDSurfG can do some 2D surface wave tomography inversion?

**Comment by nqdu** [comment]
No. 2D surface wave ray-tracing are only a part of this package, and it is designed to conduct 3D surface wave inversion. If you really want a 2D program, you could turn to [FMST](http://www.iearth.org.au/codes/FMST/).

**Comment by xichaoqiang** [comment]
Thanks for your kindly reply.I know FMST, but it is two-step tomography inversion, I think one step in Direct Surface Wave Tomography is better.

**Comment by nqdu** [comment]
If your "2D surface wave tomography inversion" means Direct Surface Wave Tomography, this package could do it. Please see instructions in `doc`.

**Comment by xichaoqiang** [comment]
Thanks.
