### ISSUE TITLE
Unable to compile the new version

### ISSUE THREAD

**Issue by boyoforex** [nqdu/JDSurfG#3]
Hi, thanks for sharing your excellent code!
I was able to compile the previous version but the new version failed as shown below:
[make[1]: Entering directory '/home/ojo/uwo/JDSurfG-master/src/SurfaceWave'
g++ -g -c -std=c++11 -I../../include -I/home/ojo/eigen-3.3.9  SurfaceWave.cpp -o SurfaceWave.o -O3 -march=native -fopenmp 
g++ -g -c -std=c++11 -I../../include -I/home/ojo/eigen-3.3.9  surfdisp.cpp -o surfdisp.o -O3 -march=native
gfortran -g -c fmm.f90 -o fmm.o  -O3 -march=native -fopenmp
gfortran -g -c fmst.f90 -o fmst.o  -O3 -march=native -fopenmp
gfortran -g -c slegn96.f90 -o slegn96.o  -O3 -march=native -fopenmp
gfortran -g -c sregn96.f90 -o sregn96.o  -O3 -march=native -fopenmp
gfortran -ffixed-line-length-none -ffloat-store -w -m64 -mcmodel=medium -g -rdynamic -c surfdisp96.f -o surfdisp96.o -O3 -march=native	
make[1]: Leaving directory '/home/ojo/uwo/JDSurfG-master/src/SurfaceWave'
make[1]: Entering directory '/home/ojo/uwo/JDSurfG-master/src/utils'
g++ -g -c -std=c++11 -I../../include -I/home/ojo/eigen-3.3.9  bkg_model.cpp -o bkg_model.o -O3 -march=native
make[1]: Leaving directory '/home/ojo/uwo/JDSurfG-master/src/utils'
make[1]: Entering directory '/home/ojo/uwo/JDSurfG-master/src/Surftomo'
g++ -g -c -std=c++11 -I../../include -I/home/ojo/eigen-3.3.9 surftomo.cpp -o surftomo.o -O3 -march=native
g++ -g -c -std=c++11 -I../../include -I/home/ojo/eigen-3.3.9 main.cpp -o main.o -O3 -march=native
g++  -o ../../bin/DSurfTomo ../utils/delsph.o ../utils/empirical.o ../utils/lsmrModule_csr.o ../SurfaceWave/fmm.o ../SurfaceWave/fmst.o ../SurfaceWave/slegn96.o ../SurfaceWave/sregn96.o ../SurfaceWave/surfdisp96.o  surftomo.o main.o ../SurfaceWave/SurfaceWave.o ../utils/gaussian.o ../utils/bkg_model.o ../SurfaceWave/surfdisp.o -lgfortran -fopenmp
../SurfaceWave/surfdisp.o: In function `surfdisp(float*, float*, float*, float*, int, double*, double*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, bool, bool)':
/home/ojo/uwo/JDSurfG-master/src/SurfaceWave/surfdisp.cpp:89: undefined reference to `surfdisp96_'
/home/ojo/uwo/JDSurfG-master/src/SurfaceWave/surfdisp.cpp:89: undefined reference to `surfdisp96_'
collect2: error: ld returned 1 exit status
Makefile:28: recipe for target 'DSurfTomo' failed
make[1]: *** [DSurfTomo] Error 1
make[1]: Leaving directory '/home/ojo/uwo/JDSurfG-master/src/Surftomo'
make[1]: Entering directory '/home/ojo/uwo/JDSurfG-master/src/gravity'
g++ -g -c -std=c++11 -I../../include  gravmat.cpp -o gravmat.o -O3 -march=native -fopenmp
g++ -g -c -std=c++11 -I../../include main.cpp -o main.o -O3 -march=native
g++  -o ../../bin/mkmat gravmat.o main.o ../utils/spherical.o ../utils/gauleg.o ../utils/empirical.o  -fopenmp -L/usr/lib/x86_64-linux-gnu -lgsl -lgslcblas -lm
make[1]: Leaving directory '/home/ojo/uwo/JDSurfG-master/src/gravity'
make[1]: Entering directory '/home/ojo/uwo/JDSurfG-master/src/JointTomo'
g++ -g -c -std=c++11 -I../../include -I/home/ojo/eigen-3.3.9 -I/usr/include main.cpp -o main.o -O3 -march=native
g++ -g -c -std=c++11 -I../../include -I/home/ojo/eigen-3.3.9 -I/usr/include JointTomo.cpp -o JointTomo.o -O3 -march=native -fopenmp
g++  -o ../../bin/JointTomo ../utils/delsph.o ../utils/empirical.o ../utils/lsmrModule_csr.o ../SurfaceWave/fmm.o ../SurfaceWave/fmst.o ../SurfaceWave/slegn96.o ../SurfaceWave/sregn96.o ../SurfaceWave/surfdisp96.o  main.o ../SurfaceWave/SurfaceWave.o ../utils/gaussian.o ../utils/spherical.o ../utils/gauleg.o ../gravity/gravmat.o ../utils/bkg_model.o ../SurfaceWave/surfdisp.o JointTomo.o -lgfortran -fopenmp -L/usr/lib/x86_64-linux-gnu -lgsl -lgslcblas -lm
../SurfaceWave/surfdisp.o: In function `surfdisp(float*, float*, float*, float*, int, double*, double*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, bool, bool)':
/home/ojo/uwo/JDSurfG-master/src/SurfaceWave/surfdisp.cpp:89: undefined reference to `surfdisp96_'
/home/ojo/uwo/JDSurfG-master/src/SurfaceWave/surfdisp.cpp:89: undefined reference to `surfdisp96_'
collect2: error: ld returned 1 exit status
Makefile:31: recipe for target 'JointTomo' failed
make[1]: *** [JointTomo] Error 1
make[1]: Leaving directory '/home/ojo/uwo/JDSurfG-master/src/JointTomo'
make[1]: Entering directory '/home/ojo/uwo/JDSurfG-master/utils'
gfortran -g -c -march=native -O3 gravity_forward.f90 -o gravity_forward.o 
gfortran -o ../bin/syngrav gravity_forward.o 
make[1]: Leaving directory '/home/ojo/uwo/JDSurfG-master/utils'
](url)

I think there is an issue within the SurfTomo folder. Kindly advise. Thanks

**Comment by nqdu** [comment]
Sorry for inconvenience.I think I forgot to upload the modified `src/SurfaceWave/surfdisp96.f`. I will fix it as soon as possible.

**Comment by Ojo-Adebayo** [comment]
Thanks. I can now compile the code successfully.
