### ISSUE TITLE
cherckboard test

### ISSUE THREAD

**Issue by xiaoxiongfeifei123** [nqdu/JDSurfG#4]
Du博您好，请问下本程序自带检测板测试时的正演程序吗？当把synthetic test中的synthetic flag设置成1的时候，程序会先进行正演计算出模拟数据吗？还是得自己根据mod.true正演得到surfdata.dat，再进行检测板反演？

**Comment by nqdu** [comment]
Hi xiaoxiongfeifei123,

Please have a look at the code snippet in `src/surftomo/main.cpp` :
```c++
// checkerboard test if required
if(tomo.param.ifsyn == 1){
    std::cout<<"Checkerboard Resolution Test Begin ..." << std::endl;
    tomo.checkerboard();
 }
```
And in the `tomo.checkerboard()` function, we synthetic `dsyn` based on `mod.true`, and substitute the original observed data (from `surfdata.dat`) with the new-synthetic one.
```c++
void DSurfTomo :: checkerboard()
{
    VectorXf dsyn(surf.num_data);
    forward(vstrue,dsyn);

    // add noise
    for(int i=0;i<surf.num_data;i++){
        //dsyn(i) *= (1.0 + param.noiselevel * gaussian());
        dsyn(i) += param.noiselevel * gaussian();
    }
    surf.obst = dsyn*1.0;
}
```
