### ISSUE TITLE
Does the program work when the scales of Bouguer gravity data and ANT data are different

### ISSUE THREAD

**Issue by WanZiXuan** [nqdu/JDSurfG#9]
Hi Du:
       Thank you for sharing the program, i'm trying to do joint inversion in a small scales . However, the scales of the bouguer gravity data(7x7km) is small than ANT's(10x10km).  I would like to know if the program work in this case?（eg. only do joint inversion in the node where both Bouguer gravity and  velocity exist)

**Comment by nqdu** [comment]
Of course, the program has no constraints on the data coverage.
